WIP: Add internal-lb config option
juju-solutions/charm-openstack-integrator pull request #60
Opened 2022-04-07 01:22 UTC by swalladge

This is ultimately a configuration option for cloud provider openstack.
This new option is passed to the openstack integrator interface,
to be used by charm-kubernetes-control-plane
to set config for cloud-provider-openstack.

2022-04-07 01:41 UTC, nobuto-m commented on config.yaml
> +      https://bugs.launchpad.net/charm-openstack-integrator/+bug/1877692
You don't have to put a bug link here. And the description can be more alighted with the upstream one:
https://github.com/kubernetes/cloud-provider-openstack/blob/003e209d5244d5cefed367a12aeaa8124ec90de4/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md#load-balancer
> internal-lb Determines whether or not to create an internal load balancer (no floating IP) by default. Default: false.

2022-04-20 13:13 UTC, addyess requested changes
Agreed, please update the config description.  Note that new parameters to interface methods should probably go at the end of the parameter list, maybe even as a keyword argument

2022-04-21 02:18 UTC, addyess approved these changes
LGTM

2022-04-21 08:28 UTC, swalladge commented
Note: don't merge yet; I'm still testing the latest changes.

2022-04-22 00:44 UTC, swalladge commented
Ok, testing finished from my end.  Ready for another review pass. :)

2022-04-22 13:09 UTC, addyess approved these changes
LGTM 🍰 🍨 🚀

2022-04-25 20:30 UTC, merged